name: Skinz-Windows-RDP-Fixed

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 1. Download and Extract Ngrok
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip -DestinationPath .
          ./ngrok.exe authtoken 3HsecokauoLiz6v7IorOCjlLMiH_3X9RgTfCZzkf1YCehKHHy

      - name: 2. Setup RDP Access
        run: |
          # إنشاء حساب الآدمن وتفعيله بنجاح
          net user Skinz KingStrongPassword123 /add
          net localgroup administrators Skinz /add
          
          # تفعيل بورت الـ RDP وتخطي جدار الحماية بالكامل
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: 3. Start Tunnel & Keep-Alive
        run: |
          # تشغيل النفق المباشر لبورت الـ RDP الافتراضي 3389
          Start-Process ./ngrok.exe -ArgumentList "tcp 3389"
          echo "=========================================================="
          echo "🔥 SERVER IS RUNNING STRONG 🔥"
          echo "=========================================================="
          
          # سكريبت الحماية لضمان استمرار السيرفر لـ 6 ساعات
          $total_seconds = 21600
          $elapsed = 0
          while ($elapsed -lt $total_seconds) {
              echo "Server Status: Active... ($elapsed / $total_seconds seconds)"
              Start-Sleep -Seconds 60
              $elapsed += 60
          }
